version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: japanese-real-estate-db
    environment:
      POSTGRES_DB: japanese_real_estate_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: japanese-real-estate-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # Backend API (will be built in later tasks)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: japanese-real-estate-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://dev_user:dev_password@postgres:5432/japanese_real_estate_dev
      REDIS_URL: redis://redis:6379
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    profiles:
      - full-stack

  # Frontend React App (will be built in later tasks)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: japanese-real-estate-frontend
    environment:
      REACT_APP_API_BASE_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    profiles:
      - full-stack

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge